.TH TVX 1 "TRACEVECTOR" "OSINT CLI"
.SH NAME
tvx \- TRACEVECTOR OSINT Investigator

.SH SYNOPSIS
tvx <type> <target> [options]

.SH DESCRIPTION
TRACEVECTOR is a modular OSINT investigation tool
for phone numbers, IP addresses, and email addresses.

.SH OPTIONS
--list-plugins
--json
--output FILE
--offline
--no-banner
--version
doctor

.SH AUTHOR
Oedx Digitals
